# 배포용 파일
version: "3.9"

services:
  promptfoo_api_test:
    image: promptfoo_api:1.0
    container_name: promptfoo_distribution
    ports:
      - "8223:3000"
      - "8334:3001"
    volumes:
      - /var/lib/promptfoo:/home/promptfoo/.promptfoo
      - /mnt/minio_goofys:/mnt/mlflow_volume
